# Generated by Django 3.2.10 on 2021-12-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbytes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='composer',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
