# Generated by Django 3.2.10 on 2021-12-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbytes', '0003_album_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='lyric',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
